spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
      discovery:
        locator:
          enabled: true
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/v*/auth*,/api/v*/auth/*
        - id: time-report-service
          uri: lb://time-report-service
          predicates:
            - Path=/api/v*/reports*,/api/v*/reports/*,/api/v*/time-entries*,/api/v*/time-entries/*
management:
  endpoint.gateway.enabled: true
  endpoints.web.exposure.include: gateway
server:
  port: 8090
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true

